config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: cdc_testing
      host: 20.229.62.148
      pass: 74jxjhiwo6z6s
      port: 5432
      schema: public
      threads: 8
      type: postgres
      user: gpadmin
  target: prod
